version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps-{{ checksum "packages.dhall" }}-{{ checksum "package.json" }}

      - run:
          command: |
            yarn add --dev purescript spago
            yarn build
            git checkout -- package.json

      - save_cache:
          paths:
            - node_modules
            - output
            - .psa-stash
          key: deps-{{ checksum "packages.dhall" }}-{{ checksum "package.json" }}

      - run:
          command: yarn jest
